// Buques de morango
export const buquesMorango = [
    {
        id: '100101',
        nome: 'Mimo',
        intro: 'Buquê mimo é um presente para todas as ocasiões.',
        desc: ['- 5 morangos banhados com chocolate', '- 2 rosas' ],
        obs: [
            '- Os morangos são banhados no chocolate, não são bombons de morango',
            '- A embalagem pode variar conforme a disponibilidade de estoque',
            '- Manter em refrigeração e consumir os morangos em até 24 horas',
            '- Nossas rosas são artificiais podendo ser utilizadas depois como uma linda decoração.',
        ],
        cartao: true,
        preco: '65,00',
        image: '/buques/mimo.jpg',
        categoria: 'morango',
    },
    {
        id: '100102',
        nome: 'Eu Te Amo',
        intro: 'Buquê eu te amo é o mais pedido por aqui! Neste buquê disponibilizamos três morangos para personalização. Podendo ser escrito nomes ou palavras pequenas.',
        desc: ['- 18 morangos banhados com chocolate e decorados', '- 1 rosa central'],
        obs: [
            '- Os morangos são banhados no chocolate, não são bombons de morango',
            '- A embalagem pode variar conforme a disponibilidade de estoque',
            '- Manter em refrigeração e consumir os morangos em até 24 horas',
            '- Nossas rosas são artificiais podendo ser utilizadas depois como uma linda decoração.',
        ],
        cartao: true,
        preco: '150,00',
        image: '/buques/euTeAmo.jpg',
        categoria: 'morango',
    },
    {
        id: '100103',
        nome: 'Sedução',
        intro: 'Buquê Sedução é poderoso e lindíssimo.',
        desc: ['- 18 morangos banhados com chocolate e decorados'],
        obs: [
            '- Os morangos são banhados no chocolate, não são bombons de morango',
            '- A embalagem pode variar conforme a disponibilidade de estoque',
            '- Caso tenha preferência de cor favor nos avisar',
            '- Manter em refrigeração e consumir os morangos em até 24 horas',
            '- Nossas rosas são artificiais podendo ser utilizadas depois como uma linda decoração.',
        ],
        cartao: true,
        preco: '140,00',
        image: '/buques/seducao.jpg',
        categoria: 'morango',
    },
    {
        id: '100104',
        nome: 'Chamego',
        intro: 'Buquê Chamego é lindo e delicado.',
        desc: ['- 14 morangos banhados com chocolate e decorados'],
        obs: [
            '- Os morangos são banhados no chocolate, não são bombons de morango',
            '- A embalagem pode variar conforme a disponibilidade de estoque',
            '- Manter em refrigeração e consumir os morangos em até 24 horas',
        ],
        cartao: true,
        preco: '110,00',
        image: '/buques/chamego.jpg',
        categoria: 'morango',
    },
    {
        id: '100105',
        nome: 'Paixão',
        intro: 'Buquê paixão é de se apaixonar mesmo. São para quem quer uma opção com mais rosas!',
        desc: ['- 16 morangos banhados com chocolate e decorados', '- 6 rosas'],
        obs: [
            '- Os morangos são banhados no chocolate, não são bombons de morango',
            '- A embalagem pode variar conforme a disponibilidade de estoque',
            '- Manter em refrigeração e consumir os morangos em até 24 horas',
            '- Nossas rosas são artificiais podendo ser utilizadas depois como uma linda decoração'
        ],
        cartao: true,
        preco: '190,00',
        image: '/buques/paixao.jpg',
        categoria: 'morango',
    },
]

// Buques de Docinho
export const buqueDocinho = [
    {
        id: '100201',
        nome: 'Doce Flor',
        desc: ['- 5 morangos', '- 2 rosas'],
        desc1: '- 10 Brigadeiros gourmet',
        desc2: '- 1 Girassol central',
        desc3: '',
        desc4: '',
        desc5: '',
        desc6: '',
        obs: [
            '- Sabores dos brigadeiros ( Brigadeiro 50%, Ninho com Nutella, Beijinho e Ferreiro)',
            '- A embalagem pode variar conforme a disponibilidade de estoque',
            '- Caso tenha preferência de cor favor nos avisar',
            '- O girassol é flor natural',
        ],
        cartao: true,
        preco: '122,00',
        image: '/buques/doceFlor.jpg',
        categoria: 'docinho',
        ingredientes: ['Côco', 'Chocolate', 'Baunilha'],
    },
]
