export const buquesMorango = [
    {
        id: '',
        nome: 'Mimo',
        desc: ['- 5 morangos', '- 2 rosas'],
        desc1: '- 5 morangos banhados com chocolate',
        desc2: '- 2 rosas',
        desc3: '',
        desc4: '',
        desc5: '',
        desc6: '',
        preco: '64.90',
        image: '/buques/docinho1.jpg',
        categoria: 'morango',
        ingredientes: ['Côco', 'Chocolate', 'Baunilha'],
    },
    {
        id: '',
        nome: 'Eu Te Amo',
        desc1: '- 5 morangos banhados com chocolate',
        desc2: '- 2 rosas',
        desc3: 'Um delicioso buque de chocolate nhamnham',
        desc4: '',
        desc5: '',
        desc6: '',
        preco: 67.9,
        image: '/buques/brigadeiros.jpg',
        categoria: 'docinhos',
        ingredientes: ['Côco', 'Chocolate', 'Baunilha'],
    },
    {
        id: '',
        nome: 'Sedução',
        desc: 'Um delicioso buque de chocolate nhamnham',
        preco: 65.9,
        image: '/buques/docinho1.jpg',
        categoria: 'bombom',
        ingredientes: ['Côco', 'Chocolate', 'Baunilha'],
    },
    {
        id: '104',
        nome: 'Chamego',
        desc: 'Um delicioso buque de chocolate nhamnham',
        preco: 62.9,
        image: '/buques/brigadeiros.jpg',
        ingredientes: ['Côco', 'Chocolate', 'Baunilha'],
    },
    {
        id: '105',
        nome: 'Paixão',
        desc: 'Um delicioso buque de chocolate nhamnham',
        preco: 61.9,
        image: '/buques/docinho1.jpg',
        ingredientes: ['Côco', 'Chocolate', 'Baunilha'],
    },
]
